import type { KnowledgeBase } from "./types"

export const MODERN_AI_KNOWLEDGE_BASE: KnowledgeBase = {
  module: "现代人工智能基础",
  version: "0.1.0",
  updatedAt: "2026-08-05",
  sources: ["KnowBalance 自编教学切片", "教师指定 AI 培训方向"],
  items: [
    {
      sourceId: "AI001",
      title: "人工智能、机器学习与深度学习",
      module: "现代人工智能基础",
      difficulty: "beginner",
      file: "knowledge_base/modern_ai/AI001_ai_ml_dl.md",
      snippet: "人工智能是让机器表现出智能行为的技术领域。",
      prerequisites: [],
      keywords: ["人工智能", "机器学习", "深度学习", "生成式AI", "AI", "ML", "DL"],
      facts: [
        { sourceId: "AI001", factId: "F001", source_id: "AI001", fact_id: "F001", content: "人工智能是让机器表现出智能行为的技术领域。" },
        { sourceId: "AI001", factId: "F002", source_id: "AI001", fact_id: "F002", content: "机器学习是人工智能中的一类方法，核心是让模型从数据中学习规律。" },
        { sourceId: "AI001", factId: "F003", source_id: "AI001", fact_id: "F003", content: "深度学习通常使用多层神经网络从数据中学习表示。" },
        { sourceId: "AI001", factId: "F004", source_id: "AI001", fact_id: "F004", content: "图灵测试是一种判断机器是否表现出智能行为的经典思想实验。" },
        { sourceId: "AI001", factId: "F005", source_id: "AI001", fact_id: "F005", content: "机器学习主要分为监督学习、无监督学习和强化学习三大类。" },
        { sourceId: "AI001", factId: "F006", source_id: "AI001", fact_id: "F006", content: "监督学习使用带标签的数据训练模型完成预测任务。" },
        { sourceId: "AI001", factId: "F007", source_id: "AI001", fact_id: "F007", content: "生成式人工智能能够根据输入条件生成文本、图像等新内容。" },
        { sourceId: "AI001", factId: "F008", source_id: "AI001", fact_id: "F008", content: "机器学习算法的效果高度依赖训练数据的质量与规模。" },
        { sourceId: "AI001", factId: "F009", source_id: "AI001", fact_id: "F009", content: "深度学习通常需要比传统机器学习更多的数据与算力。" },
        { sourceId: "AI001", factId: "F010", source_id: "AI001", fact_id: "F010", content: "人工智能系统常通过感知、推理、学习等能力组合完成复杂任务。" },
        { sourceId: "AI001", factId: "F011", source_id: "AI001", fact_id: "F011", content: "从人工智能到机器学习再到深度学习，是逐步细化的技术路线。" },
        { sourceId: "AI001", factId: "F012", source_id: "AI001", fact_id: "F012", content: "强化学习通过与环境交互获得奖励信号来改进策略。" },
      ],
      examples: [
        { title: "区分 AI、ML、DL", code: "concepts = [\"AI\", \"ML\", \"DL\"]\nfor concept in concepts:\n    print(concept)", explanation: "AI 是更大的领域，ML 是 AI 的方法之一，DL 是常见的 ML 技术路线之一。" },
        { title: "判断是否属于机器学习", code: "rule_based = False\nml_based = True\nprint(rule_based, ml_based)", explanation: "靠人工写死规则不属于机器学习，从数据中学习规律才属于机器学习。" },
        { title: "神经网络分层示意", code: "layers = [\"输入层\", \"隐藏层\", \"输出层\"]\nfor layer in layers:\n    print(layer)", explanation: "深度学习通常由多层神经网络组成，逐层提取数据的表示。" },
      ],
      practiceTasks: [
        "用自己的话说明 AI、ML、DL 的层级关系",
        "判断一个垃圾邮件分类器属于 AI、ML 还是 DL 应用",
        "举一个生活中的机器学习例子并说明它学习到了什么规律",
        "说明生成式 AI 与传统机器学习程序的主要区别",
      ],
      quizItems: [
        { level: 1, type: "choice", question: "机器学习的核心特征是什么？", options: ["从数据中学习规律", "只靠人工写死规则", "只能处理图像", "只能生成文本"], answer: "从数据中学习规律", sourceId: "AI001", factId: "F002" },
        { level: 2, type: "short_answer", question: "说明人工智能、机器学习、深度学习三者的包含关系。", answer: "人工智能是大领域，机器学习是其中一类方法，深度学习通常是基于多层神经网络的机器学习方法。", sourceId: "AI001", factId: "F003" },
        { level: 2, type: "debugging", question: "判断正误：深度学习等同于所有人工智能。", answer: "错误。深度学习是人工智能中的一种技术路线，不等同于全部人工智能。", sourceId: "AI001", factId: "F001" },
        { level: 3, type: "practice", question: "给出一个日常 AI 应用，并说明它可能用到机器学习的哪一部分思想。", answer: "能指出应用场景，并说明从数据中学习规律的思想。", sourceId: "AI001", factId: "F002" },
        { level: 1, type: "choice", question: "图灵测试主要用来判断什么？", options: ["机器是否表现出智能行为", "机器运算速度", "机器耗电量", "机器价格"], answer: "机器是否表现出智能行为", sourceId: "AI001", factId: "F004" },
        { level: 2, type: "short_answer", question: "为什么说深度学习通常需要比传统机器学习更多的数据？", answer: "因为深度学习通常使用多层神经网络，参数量大，需要更多数据来学习表示。", sourceId: "AI001", factId: "F009" },
        { level: 3, type: "debugging", question: "判断正误：生成式 AI 只能生成文本，不能生成图像。", answer: "错误。生成式人工智能能够根据输入条件生成文本、图像等多种新内容。", sourceId: "AI001", factId: "F007" },
      ],
    },
    {
      sourceId: "AI002",
      title: "数据集、特征与标签",
      module: "现代人工智能基础",
      difficulty: "beginner",
      file: "knowledge_base/modern_ai/AI002_dataset_feature_label.md",
      snippet: "数据集是用于训练、验证或测试模型的数据集合。",
      prerequisites: ["AI001"],
      keywords: ["数据集", "特征", "标签", "样本", "训练数据", "测试数据"],
      facts: [
        { sourceId: "AI002", factId: "F001", source_id: "AI002", fact_id: "F001", content: "数据集是用于训练、验证或测试模型的数据集合。" },
        { sourceId: "AI002", factId: "F002", source_id: "AI002", fact_id: "F002", content: "特征是描述样本的输入信息。" },
        { sourceId: "AI002", factId: "F003", source_id: "AI002", fact_id: "F003", content: "标签是监督学习中模型需要预测的目标结果。" },
        { sourceId: "AI002", factId: "F004", source_id: "AI002", fact_id: "F004", content: "训练数据、验证数据和测试数据通常来自同一个数据集的不同划分。" },
        { sourceId: "AI002", factId: "F005", source_id: "AI002", fact_id: "F005", content: "特征选择会影响模型的训练效果与可解释性。" },
        { sourceId: "AI002", factId: "F006", source_id: "AI002", fact_id: "F006", content: "数值型特征适合直接输入大多数机器学习模型。" },
        { sourceId: "AI002", factId: "F007", source_id: "AI002", fact_id: "F007", content: "标签通常由人工标注或已有答案整理得到。" },
        { sourceId: "AI002", factId: "F008", source_id: "AI002", fact_id: "F008", content: "无标签数据可以用于无监督学习或预训练阶段。" },
        { sourceId: "AI002", factId: "F009", source_id: "AI002", fact_id: "F009", content: "特征工程是指把原始数据转换成更适合模型学习的输入。" },
        { sourceId: "AI002", factId: "F010", source_id: "AI002", fact_id: "F010", content: "样本是数据集中一条独立的数据记录。" },
        { sourceId: "AI002", factId: "F011", source_id: "AI002", fact_id: "F011", content: "数据类型和质量直接影响模型能学到的规律。" },
        { sourceId: "AI002", factId: "F012", source_id: "AI002", fact_id: "F012", content: "特征和标签的对应关系构成监督学习的训练依据。" },
      ],
      examples: [
        { title: "成绩预测数据", code: "sample = {\"hours\": 3, \"attendance\": 0.9, \"passed\": True}\nfeatures = [sample[\"hours\"], sample[\"attendance\"]]\nlabel = sample[\"passed\"]\nprint(features, label)", explanation: "学习时长和出勤率可作为特征，是否通过可作为标签。" },
        { title: "构造样本字典", code: "samples = [\n    {\"hours\": 2, \"passed\": False},\n    {\"hours\": 5, \"passed\": True},\n]\nfor s in samples:\n    print(s)", explanation: "每个样本由特征和标签组成，这里 hours 是特征，passed 是标签。" },
        { title: "特征类型对比", code: "numeric = 3.5\ncategory = \"文科\"\nprint(type(numeric), type(category))", explanation: "数值型特征与类别型特征的表示方式不同，需要按类型处理。" },
      ],
      practiceTasks: [
        "为垃圾邮件识别任务列出 3 个可能特征",
        "判断房价预测任务中的标签是什么",
        "把根据天气预测是否下雨的任务拆成特征与标签",
        "说明为什么训练数据和测试数据不能混用",
      ],
      quizItems: [
        { level: 1, type: "choice", question: "监督学习中模型要预测的目标通常叫作什么？", options: ["标签", "注释", "变量名", "索引"], answer: "标签", sourceId: "AI002", factId: "F003" },
        { level: 2, type: "short_answer", question: "在学生成绩预测中，学习时长可以作为特征还是标签？为什么？", answer: "可以作为特征，因为它是描述样本的输入信息。", sourceId: "AI002", factId: "F002" },
        { level: 2, type: "debugging", question: "判断正误：训练数据里任何字段都一定是标签。", answer: "错误。特征是输入信息，标签才是要预测的目标结果。", sourceId: "AI002", factId: "F003" },
        { level: 3, type: "practice", question: "为“预测学生是否通过考试”设计 3 个特征和 1 个标签。", answer: "能给出学习时长、出勤率、历史成绩等特征，并以是否通过作为标签。", sourceId: "AI002", factId: "F001" },
        { level: 1, type: "choice", question: "特征工程的主要作用是什么？", options: ["把原始数据转换成更适合模型学习的输入", "删除所有数据", "提高电脑性能", "替代标签"], answer: "把原始数据转换成更适合模型学习的输入", sourceId: "AI002", factId: "F009" },
        { level: 2, type: "short_answer", question: "无标签数据可以用于哪些场景？", answer: "无标签数据可以用于无监督学习或预训练阶段。", sourceId: "AI002", factId: "F008" },
        { level: 3, type: "debugging", question: "判断正误：所有数据都必须经过人工标注才能用于机器学习。", answer: "错误。无标签数据可以用于无监督学习或预训练阶段。", sourceId: "AI002", factId: "F008" },
      ],
    },
    {
      sourceId: "AI003",
      title: "训练集、测试集与过拟合",
      module: "现代人工智能基础",
      difficulty: "basic",
      file: "knowledge_base/modern_ai/AI003_train_test_overfit.md",
      snippet: "训练集用于拟合模型，测试集用于评估模型在未见数据上的表现。",
      prerequisites: ["AI002"],
      keywords: ["训练集", "测试集", "验证集", "过拟合", "泛化", "评估"],
      facts: [
        { sourceId: "AI003", factId: "F001", source_id: "AI003", fact_id: "F001", content: "训练集用于拟合模型。" },
        { sourceId: "AI003", factId: "F002", source_id: "AI003", fact_id: "F002", content: "测试集用于评估模型在未见数据上的表现。" },
        { sourceId: "AI003", factId: "F003", source_id: "AI003", fact_id: "F003", content: "过拟合是指模型过度记住训练数据而在新数据上表现变差。" },
        { sourceId: "AI003", factId: "F004", source_id: "AI003", fact_id: "F004", content: "验证集用于在训练过程中调参并选择模型。" },
        { sourceId: "AI003", factId: "F005", source_id: "AI003", fact_id: "F005", content: "数据划分越随机，训练集和测试集越能代表整体分布。" },
        { sourceId: "AI003", factId: "F006", source_id: "AI003", fact_id: "F006", content: "模型在训练集上表现好而测试集表现差是过拟合的典型信号。" },
        { sourceId: "AI003", factId: "F007", source_id: "AI003", fact_id: "F007", content: "正则化是缓解过拟合的常用手段之一。" },
        { sourceId: "AI003", factId: "F008", source_id: "AI003", fact_id: "F008", content: "增加训练数据量通常可以降低过拟合风险。" },
        { sourceId: "AI003", factId: "F009", source_id: "AI003", fact_id: "F009", content: "交叉验证可以更充分地利用有限数据进行模型评估。" },
        { sourceId: "AI003", factId: "F010", source_id: "AI003", fact_id: "F010", content: "测试集只能使用一次，反复用它调参会导致评估结果失真。" },
        { sourceId: "AI003", factId: "F011", source_id: "AI003", fact_id: "F011", content: "欠拟合是指模型过于简单，在训练集和测试集上都表现不佳。" },
        { sourceId: "AI003", factId: "F012", source_id: "AI003", fact_id: "F012", content: "训练误差和测试误差的差距可以反映模型的泛化能力。" },
      ],
      examples: [
        { title: "划分训练和测试样本", code: "data = list(range(10))\ntrain = data[:8]\ntest = data[8:]\nprint(\"train\", train)\nprint(\"test\", test)", explanation: "训练样本用于学习规律，测试样本用于检查模型面对新样本的表现。" },
        { title: "打乱后按比例划分", code: "import random\nsamples = list(range(100))\nrandom.shuffle(samples)\ntrain = samples[:80]\ntest = samples[80:]\nprint(len(train), len(test))", explanation: "先打乱再按比例划分，能让训练集和测试集更接近整体分布。" },
        { title: "过拟合信号示意", code: "train_acc = 0.99\ntest_acc = 0.62\nprint(train_acc > test_acc)", explanation: "训练准确率远高于测试准确率，是过拟合的典型信号。" },
      ],
      practiceTasks: [
        "解释为什么不能只看训练集准确率",
        "举例说明过拟合的表现",
        "设计一个防止过拟合的简单方案",
        "解释为什么测试集不能反复用于调参",
      ],
      quizItems: [
        { level: 1, type: "choice", question: "测试集的主要用途是什么？", options: ["评估未见数据表现", "保存代码", "替代标签", "删除特征"], answer: "评估未见数据表现", sourceId: "AI003", factId: "F002" },
        { level: 2, type: "short_answer", question: "为什么训练集准确率很高不一定代表模型好？", answer: "模型可能过拟合，过度记住训练数据，在新数据上表现变差。", sourceId: "AI003", factId: "F003" },
        { level: 2, type: "debugging", question: "判断正误：模型在训练集上 100% 正确，就一定能在新数据上 100% 正确。", answer: "错误。训练集表现不能替代测试集泛化评估。", sourceId: "AI003", factId: "F002" },
        { level: 3, type: "practice", question: "给定 100 条样本，设计一个简单的训练集/测试集划分方案。", answer: "可将 80 条作为训练集、20 条作为测试集，并说明测试集用于未见数据评估。", sourceId: "AI003", factId: "F001" },
        { level: 1, type: "choice", question: "下列哪个是缓解过拟合的常用手段？", options: ["正则化", "删除测试集", "增加无关特征", "不做任何处理"], answer: "正则化", sourceId: "AI003", factId: "F007" },
        { level: 2, type: "short_answer", question: "为什么测试集不能反复用于调参？", answer: "因为反复用测试集调参会导致评估结果失真，测试集只能使用一次。", sourceId: "AI003", factId: "F010" },
        { level: 3, type: "debugging", question: "判断正误：模型在训练集和测试集上都表现不佳，说明模型过拟合了。", answer: "错误。训练集和测试集表现都差更可能是欠拟合，过拟合是训练集好而测试集差。", sourceId: "AI003", factId: "F011" },
      ],
    },
    {
      sourceId: "AI004",
      title: "分类、回归与聚类任务",
      module: "现代人工智能基础",
      difficulty: "basic",
      file: "knowledge_base/modern_ai/AI004_ml_tasks.md",
      snippet: "分类任务预测离散类别，回归任务预测连续数值。",
      prerequisites: ["AI002"],
      keywords: ["分类", "回归", "聚类", "预测", "类别", "连续数值"],
      facts: [
        { sourceId: "AI004", factId: "F001", source_id: "AI004", fact_id: "F001", content: "分类任务预测离散类别。" },
        { sourceId: "AI004", factId: "F002", source_id: "AI004", fact_id: "F002", content: "回归任务预测连续数值。" },
        { sourceId: "AI004", factId: "F003", source_id: "AI004", fact_id: "F003", content: "聚类任务把样本按相似性分组，通常不依赖人工给定标签。" },
        { sourceId: "AI004", factId: "F004", source_id: "AI004", fact_id: "F004", content: "二分类问题的输出只有两个类别选项。" },
        { sourceId: "AI004", factId: "F005", source_id: "AI004", fact_id: "F005", content: "多分类任务需要为每个样本从多个类别中选出一个。" },
        { sourceId: "AI004", factId: "F006", source_id: "AI004", fact_id: "F006", content: "线性回归是经典的回归算法之一，输出连续数值。" },
        { sourceId: "AI004", factId: "F007", source_id: "AI004", fact_id: "F007", content: "K 均值算法是常用的聚类方法，按距离把样本分组。" },
        { sourceId: "AI004", factId: "F008", source_id: "AI004", fact_id: "F008", content: "逻辑回归虽然名字带回归，但常用于分类任务。" },
        { sourceId: "AI004", factId: "F009", source_id: "AI004", fact_id: "F009", content: "聚类结果没有标准答案，需要结合业务含义解读。" },
        { sourceId: "AI004", factId: "F010", source_id: "AI004", fact_id: "F010", content: "分类和回归都属于监督学习，聚类属于无监督学习。" },
        { sourceId: "AI004", factId: "F011", source_id: "AI004", fact_id: "F011", content: "特征缩放可以避免数值范围大的特征主导距离计算。" },
        { sourceId: "AI004", factId: "F012", source_id: "AI004", fact_id: "F012", content: "评估分类任务常用准确率，评估回归任务常用误差指标。" },
      ],
      examples: [
        { title: "任务类型判断", code: "tasks = {\"垃圾邮件识别\": \"分类\", \"房价预测\": \"回归\", \"用户分群\": \"聚类\"}\nfor name, kind in tasks.items():\n    print(name, kind)", explanation: "不同任务的输出形式决定了它属于分类、回归还是聚类。" },
        { title: "三类任务输出对比", code: "task = {\"垃圾邮件识别\": \"离散类别\", \"房价预测\": \"连续数值\", \"用户分群\": \"分组结果\"}\nfor name, output in task.items():\n    print(name, output)", explanation: "输出形式决定任务类型：离散类别是分类，连续数值是回归，分组结果是聚类。" },
        { title: "逻辑回归的用途", code: "from sklearn.linear_model import LogisticRegression\nmodel = LogisticRegression()\nprint(type(model).__name__)", explanation: "逻辑回归虽然名字带回归，但通常用于分类任务。" },
      ],
      practiceTasks: [
        "判断成绩等级预测属于分类还是回归",
        "说明用户分群为什么常被视为聚类任务",
        "判断预测明天气温属于哪类任务并说明理由",
        "说明聚类结果为什么需要结合业务含义解读",
      ],
      quizItems: [
        { level: 1, type: "choice", question: "预测房屋价格通常属于哪类任务？", options: ["回归", "分类", "聚类", "排序"], answer: "回归", sourceId: "AI004", factId: "F002" },
        { level: 2, type: "short_answer", question: "垃圾邮件识别为什么通常是分类任务？", answer: "因为它预测的是垃圾/非垃圾等离散类别。", sourceId: "AI004", factId: "F001" },
        { level: 2, type: "debugging", question: "判断正误：聚类任务一定需要每个样本都有人工标签。", answer: "错误。聚类通常按相似性分组，不依赖人工给定标签。", sourceId: "AI004", factId: "F003" },
        { level: 3, type: "practice", question: "分别给出一个分类、回归、聚类的教育场景例子。", answer: "能区分离散类别、连续数值和相似性分组三类输出。", sourceId: "AI004", factId: "F001" },
        { level: 1, type: "choice", question: "逻辑回归虽然名字带回归，但通常用于什么任务？", options: ["分类任务", "聚类任务", "降维任务", "生成任务"], answer: "分类任务", sourceId: "AI004", factId: "F008" },
        { level: 2, type: "short_answer", question: "为什么聚类结果需要结合业务含义解读？", answer: "因为聚类结果没有标准答案，需要结合业务含义解读。", sourceId: "AI004", factId: "F009" },
        { level: 3, type: "debugging", question: "判断正误：分类和回归都属于无监督学习。", answer: "错误。分类和回归都属于监督学习，聚类属于无监督学习。", sourceId: "AI004", factId: "F010" },
      ],
    },
    {
      sourceId: "AI005",
      title: "大语言模型、提示词与 RAG",
      module: "现代人工智能基础",
      difficulty: "intermediate",
      file: "knowledge_base/modern_ai/AI005_llm_prompt_rag.md",
      snippet: "大语言模型根据上下文生成文本，但可能产生不受证据支持的幻觉内容。",
      prerequisites: ["AI001", "AI002"],
      keywords: ["大语言模型", "LLM", "提示词", "prompt", "RAG", "检索增强生成", "幻觉", "上下文"],
      facts: [
        { sourceId: "AI005", factId: "F001", source_id: "AI005", fact_id: "F001", content: "大语言模型根据上下文生成文本。" },
        { sourceId: "AI005", factId: "F002", source_id: "AI005", fact_id: "F002", content: "RAG 通过检索外部知识为生成过程提供证据。" },
        { sourceId: "AI005", factId: "F003", source_id: "AI005", fact_id: "F003", content: "幻觉是指模型生成了不受可靠证据支持的内容。" },
        { sourceId: "AI005", factId: "F004", source_id: "AI005", fact_id: "F004", content: "大语言模型基于海量文本训练，能够完成翻译、总结等任务。" },
        { sourceId: "AI005", factId: "F005", source_id: "AI005", fact_id: "F005", content: "提示词是用户给模型的输入指令，影响输出的质量。" },
        { sourceId: "AI005", factId: "F006", source_id: "AI005", fact_id: "F006", content: "上下文窗口限制了大语言模型单次能处理的文本长度。" },
        { sourceId: "AI005", factId: "F007", source_id: "AI005", fact_id: "F007", content: "RAG 先检索与问题相关的资料，再把资料交给模型生成回答。" },
        { sourceId: "AI005", factId: "F008", source_id: "AI005", fact_id: "F008", content: "提示词越明确具体，模型越容易给出符合预期的回答。" },
        { sourceId: "AI005", factId: "F009", source_id: "AI005", fact_id: "F009", content: "检索增强生成可以把外部知识库与模型生成能力结合起来。" },
        { sourceId: "AI005", factId: "F010", source_id: "AI005", fact_id: "F010", content: "减少幻觉可以在提示词中要求模型只依据给定证据回答。" },
        { sourceId: "AI005", factId: "F011", source_id: "AI005", fact_id: "F011", content: "大语言模型本身不包含最新知识，知识更新依赖外部检索。" },
        { sourceId: "AI005", factId: "F012", source_id: "AI005", fact_id: "F012", content: "温度参数控制生成文本的随机程度，较低温度输出更稳定。" },
      ],
      examples: [
        { title: "RAG 证据先行", code: "evidence = \"Python 使用 = 进行变量赋值。\"\nquestion = \"Python 如何给变量赋值？\"\nanswer = evidence\nprint(answer)", explanation: "先检索证据，再围绕证据生成回答，可以降低无依据生成。" },
        { title: "提示词约束证据", code: "evidence = \"Python 使用 = 进行变量赋值。\"\nprompt = \"请只根据以下证据回答：\" + evidence\nprint(prompt)", explanation: "在提示词中要求模型只依据给定证据回答，可以减少幻觉。" },
        { title: "RAG 三步流程", code: "steps = [\"检索证据\", \"生成回答\", \"核对证据\"]\nfor step in steps:\n    print(step)", explanation: "RAG 先检索外部知识，再生成回答，最后核对回答是否被证据支持。" },
      ],
      practiceTasks: [
        "写一个提示词，要求回答必须引用给定证据",
        "判断一段回答是否包含无证据支持的内容",
        "写一个包含只依据证据回答要求的提示词",
        "说明上下文窗口对问答场景的限制",
      ],
      quizItems: [
        { level: 1, type: "choice", question: "RAG 的核心作用是什么？", options: ["为生成提供外部证据", "删除所有数据", "只做图像处理", "替代编程语言"], answer: "为生成提供外部证据", sourceId: "AI005", factId: "F002" },
        { level: 2, type: "short_answer", question: "什么是大语言模型幻觉？", answer: "模型生成了不受可靠证据支持的内容。", sourceId: "AI005", factId: "F003" },
        { level: 2, type: "debugging", question: "判断正误：只要用了大语言模型，生成内容就一定完全正确。", answer: "错误。大语言模型可能生成幻觉，需要证据和审核。", sourceId: "AI005", factId: "F003" },
        { level: 3, type: "practice", question: "设计一个 RAG 问答流程，说明检索、生成、审核三步分别做什么。", answer: "能说明先检索证据，再生成回答，最后检查回答是否被证据支持。", sourceId: "AI005", factId: "F002" },
        { level: 1, type: "choice", question: "提示词越明确具体，模型给出的回答会怎样？", options: ["越容易符合预期", "一定完全正确", "一定更短", "完全没有影响"], answer: "越容易符合预期", sourceId: "AI005", factId: "F008" },
        { level: 2, type: "short_answer", question: "为什么大语言模型的知识更新依赖外部检索？", answer: "因为大语言模型本身不包含最新知识，知识更新依赖外部检索。", sourceId: "AI005", factId: "F011" },
        { level: 3, type: "debugging", question: "判断正误：降低温度参数可以让生成结果更稳定。", answer: "正确。温度参数控制生成文本的随机程度，较低温度输出更稳定。", sourceId: "AI005", factId: "F012" },
      ],
    },
    {
      sourceId: "AI006",
      title: "多智能体协作与事实审核",
      module: "现代人工智能基础",
      difficulty: "intermediate",
      file: "knowledge_base/modern_ai/AI006_multi_agent_audit.md",
      snippet: "多智能体系统通过职责分工让不同 Agent 执行诊断、生成、审核和决策。",
      prerequisites: ["AI005"],
      keywords: ["多智能体", "Agent", "协作", "事实审核", "角色分工", "辩论", "纠偏"],
      facts: [
        { sourceId: "AI006", factId: "F001", source_id: "AI006", fact_id: "F001", content: "多智能体系统通过职责分工让不同 Agent 执行不同任务。" },
        { sourceId: "AI006", factId: "F002", source_id: "AI006", fact_id: "F002", content: "事实审核 Agent 用于检查生成内容是否受到证据支持。" },
        { sourceId: "AI006", factId: "F003", source_id: "AI006", fact_id: "F003", content: "生成、审核和决策分离可以降低单一生成模块直接发布错误内容的风险。" },
        { sourceId: "AI006", factId: "F004", source_id: "AI006", fact_id: "F004", content: "多智能体协作通常包含诊断、生成、审核与决策等角色。" },
        { sourceId: "AI006", factId: "F005", source_id: "AI006", fact_id: "F005", content: "审核 Agent 发现内容缺乏证据时会把结果退回重写。" },
        { sourceId: "AI006", factId: "F006", source_id: "AI006", fact_id: "F006", content: "多智能体系统通过消息传递或共享状态进行协作。" },
        { sourceId: "AI006", factId: "F007", source_id: "AI006", fact_id: "F007", content: "决策 Agent 根据审核结果决定下一步的学习或生成动作。" },
        { sourceId: "AI006", factId: "F008", source_id: "AI006", fact_id: "F008", content: "角色分离让每个 Agent 只关注自己负责的环节，职责更清晰。" },
        { sourceId: "AI006", factId: "F009", source_id: "AI006", fact_id: "F009", content: "多智能体协作可以降低单点生成错误的传播范围。" },
        { sourceId: "AI006", factId: "F010", source_id: "AI006", fact_id: "F010", content: "事实审核需要在生成之后、发布之前执行。" },
        { sourceId: "AI006", factId: "F011", source_id: "AI006", fact_id: "F011", content: "多智能体系统的设计重点是明确每个 Agent 的输入输出接口。" },
        { sourceId: "AI006", factId: "F012", source_id: "AI006", fact_id: "F012", content: "协同决策是指多个 Agent 综合各自信息后共同确定行动方案。" },
      ],
      examples: [
        { title: "Agent 分工示例", code: "agents = [\"诊断Agent\", \"生成Agent\", \"审核Agent\", \"决策Agent\"]\nfor agent in agents:\n    print(agent)", explanation: "不同 Agent 分别负责学情诊断、内容生成、事实审核和下一步学习决策。" },
        { title: "审核不通过退回", code: "passed = False\nif not passed:\n    print(\"退回重写\")\nelse:\n    print(\"发布\")", explanation: "事实审核不通过时，生成内容应退回重写而不是直接发布。" },
        { title: "四步协作流程", code: "flow = [\"诊断\", \"生成\", \"审核\", \"决策\"]\nfor step in flow:\n    print(step)", explanation: "多智能体按诊断、生成、审核、决策四步分工协作。" },
      ],
      practiceTasks: [
        "设计一个三 Agent 教学流程",
        "说明为什么生成和审核应该分离",
        "为课程问答场景设计两个 Agent 的分工",
        "说明审核 Agent 在什么情况下应退回生成结果",
      ],
      quizItems: [
        { level: 1, type: "choice", question: "事实审核 Agent 的主要职责是什么？", options: ["检查生成内容是否有证据支持", "随机删除知识库", "只负责界面配色", "替代所有学习者输入"], answer: "检查生成内容是否有证据支持", sourceId: "AI006", factId: "F002" },
        { level: 2, type: "short_answer", question: "为什么多智能体系统要做角色分工？", answer: "角色分工能让不同 Agent 执行诊断、生成、审核和决策等不同任务。", sourceId: "AI006", factId: "F001" },
        { level: 2, type: "debugging", question: "判断正误：生成 Agent 生成内容后不需要审核就可以直接发布。", answer: "错误。生成内容需要事实审核，避免无证据或错误内容直接发布。", sourceId: "AI006", factId: "F002" },
        { level: 3, type: "practice", question: "为个性化教学平台设计“诊断-生成-审核-决策”四步 Agent 协作流程。", answer: "能说明诊断学习者、生成资源、审核事实、根据结果做学习决策。", sourceId: "AI006", factId: "F003" },
        { level: 1, type: "choice", question: "审核 Agent 发现内容缺乏证据时应该怎么做？", options: ["把结果退回重写", "直接发布", "删除知识库", "忽略问题"], answer: "把结果退回重写", sourceId: "AI006", factId: "F005" },
        { level: 2, type: "short_answer", question: "事实审核应该在什么时机执行？", answer: "事实审核需要在生成之后、发布之前执行。", sourceId: "AI006", factId: "F010" },
        { level: 3, type: "debugging", question: "判断正误：多智能体系统中每个 Agent 的输入输出接口不需要明确。", answer: "错误。多智能体系统的设计重点是明确每个 Agent 的输入输出接口。", sourceId: "AI006", factId: "F011" },
      ],
    },
  ],
}

